# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    name: Build java ${{ matrix.java }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-20.04
          - ubuntu-22.04
        java:
          - 17
          
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up JDK ${{matrix.java}}
        uses: actions/setup-java@v3
        with:
          java-version: ${{matrix.java}}
          distribution: 'adopt'
          cache: maven
      
      - name: Build Test and Package
        run: ./mvnw -B package

      - name: Output Version
        id: maven_version
        run: |
          cat target/classes/version.properties >> $GITHUB_OUTPUT

      - name: Set artifact parameters
        if: matrix.os == 'ubuntu-20.04'
        id: artifact_parameters
        uses: actions/github-script@v6
        with:
          script: |
            core.setOutput('artifact_name', `application-jar`);
            core.setOutput('artifact_path', `target`);

      - name: Upload application jar artifact
        if: matrix.os == 'ubuntu-20.04'
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.artifact_parameters.outputs.artifact_name }}
          path: ${{ steps.artifact_parameters.outputs.artifact_path }}/homework-${{ steps.maven_version.outputs.version }}.jar
          if-no-files-found: error
      
